---
- name: Terminate instances
  hosts: localhost

  vars:
    instance_id: i-02f97e70735b5f501
    region: us-east-1

       
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        instance_ids: "{{ instance_id }}"