---
- name: Terminate instances
  hosts: localhost

  vars:
    instance_id: i-02f97e70735b5f501
    region: us-east-1
    aws_access_key: AKIAYXAVFKD5S3R6TAGB
    aws_secret_key: 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   
       
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        instance_ids: "{{ instance_id }}"