- name: Terminate instances
  hosts: localhost
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        region: us-east-1
        instance_ids: 'i-02f97e70735b5f501'
      register: ec2_termination

    - debug:
        var: ec2_termination
