---
- name: reboot devices
  hosts: ansible_host
  become: yes
  tasks:
    - name: Servers to reboot
      ansible.builtin.command: reboot now
      ansible_user: ec2-user
      ansible_ssh_private_key_file: clientkey.pem