---
- name: reboot devices
  hosts: ansible_host
  become: yes
  tasks:
    - name: Servers to reboot
      ansible.builtin.command: reboot now

- name: Another play for custom inventory
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    ansible_inventory_sources:
      - inventory.ini
    ansible_user: ec2-user
    ansible_ssh_private_key_file: clientkey.pem
