---
- name: reboot devices
  hosts: ansible_host
  become: yes
  vars:
    ansible_inventory_sources:
      - inventory.ini
    ansible_user: ec2-user
    ansible_ssh_private_key_file: clientkey.pem  
  tasks:
    - name: Servers to reboot
      ansible.builtin.command: reboot now
    
