---
# handlers file for post-install
    - name: Restart NTP on Ubuntu
      service:
        name: ntp
        state: restarted
        enabled: yes
      when: ansible_distribution == "Ubuntu"

    - name: Restart NTP on Centos
      service:
         name: chronyd
         state: restarted
         enabled: yes
      when: ansible_distribution == "CentOS"

    - name: fetch list of your_username
      command: getent passwd
      register: existing_users
