---
- name: Provisioning Servers by anbar
  hosts: all
  become: yes
  roles:
    - geerlingguy.java
    - role: post-install
      vars:
        ntp0: 2.ee.pool.ntp.org
        ntp1: 1.in.pool.ntp.org
        ntp2: 2.in.pool.ntp.org
        ntp3: 3.north-america.pool.ntp.org

