---

- name: Terminate EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    instance_id: i-02f97e70735b5f501
    region: us-east-1
    aws_access_key: AKIAYXAVFKD5S3R6TAGB
    aws_secret_key: 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   
       
  tasks:
    - name: Terminate EC2 Instance
      amazon.aws.aws_ec2:
        instance_ids: "{{ instance_id }}"
        state: "absent"
        region: "{{ region }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      register: ec2_termination

    - debug:
        var: ec2_termination
